#!/usr/bin/perl
use strict;
# Get configuration of gutenbach

my $zephyr_class = "sipb-test";
my $host = `hostname`;
my $queue = "gutenbach";
my $mixer = "Headphone";
my $channel = "Front Left";

# Configuration
my $config_file = "/usr/lib/gutenbach/gutenbach-filter-config.pl";
if (-r $config_file) {
    # Inline the configuration file
    local $/;
    my $fh;
    open $fh, $config_file;
    eval <$fh>;
}

my %config = (
    'zephyr-class' => $zephyr_class,
    'host' => $host,
    'queue' => $queue,
    'mixer' => $mixer,
    'channel' => $channel,
);

foreach my $argv (@ARGV)
{
    #print $argv . "\n";
    print $config{$argv};
}
