#!/bin/sh
PATH="$(dirname $0):$PATH"

mixer=$(gutenbach-get-config mixer)
channel="$(gutenbach-get-config channel)"

amixer set $mixer "$2" | grep "$channel" \
 | perl -lne 'print $1 if (/: Playback ([0-9]+)/)'

volume-zephyr
