#!/bin/bash
cat <<EOF
Usage: remctl zsr.mit.edu <command> <subcommand> [..args..]
Commands:
  volume up        - increment volume
  volume down      - decrement volume
  volume get       - get volume
  volume set [vol] - set volume, in range 0..31
  volume mute      - zero volume
  volume help,
   help <anything> - print this help

'v', 'u', 'd' abbreviate 'volume', 'up', 'down' respectively.
EOF
