#!/bin/bash

echo "Stopping view-gutenbach-queue..."
killall -q "/usr/lib/gutenbach/queue/view-gutenbach-queue"
echo "Stopping build-gutenbach-queue..."
killall -q "/usr/lib/gutenbach/queue/build-gutenbach-queue"
echo "Stopping queue..."
killall -q "/usr/lib/gutenbach/queue/queue"
echo "Stopping exiftool..."
killall -q "/usr/bin/exiftool"
echo "Stopping watch..."
killall -q "/usr/bin/watch"
echo "Done."