#!/bin/bash
easy_install -i http://www.turbogears.org/2.0/downloads/current/index tg.devtools
# deal with bugs that happen during install
easy_install tg.devtools
easy_install tg.devtools
easy_install flup
easy_install tw.forms

# Install remctl
VERSION="2.14"
wget http://archives.eyrie.org/software/kerberos/remctl-$VERSION.tar.gz
tar -xf remctl-$VERSION.tar.gz
rm remctl-$VERSION.tar.gz
cd remctl-$VERSION
./configure --enable-python
make
cd python
python setup.py build
python setup.py install
cd ../..
rm -rf remctl-$VERSION

python setup.py develop

paster --help
