#!/bin/sh

echo "Removing gutenbach printer..." >&2

if [ -e /usr/lib/gutenbach/config/printername ]; then
    printername="$(cat /usr/lib/gutenbach/config/printername)"

    lpadmin -x "$printername"

else
    echo "Error: /usr/lib/gutenbach/config/printername does not exist"
fi