#!/bin/sh

if [ -e /usr/lib/gutenbach/config/printername ]; then
    printername="$(cat /usr/lib/gutenbach/config/printername)"

    lpadmin -p "$printername" \
	    -E -v gutenbach:/dev/null \
	    -D "Gutenbach Music Spooler"

else
    echo "Error: /usr/lib/gutenbach/config/printername does not exist"
    exit 1
fi