#!/bin/sh
PATH="$(dirname $0):$PATH"

mixer=$(/usr/lib/gutenbach/gutenbach-get-config mixer)
channel=$(/usr/lib/gutenbach/gutenbach-get-config channel)

amixer get $mixer | grep "$channel" \
 | perl -lne 'print $1 if (/: Playback ([0-9]+)/)'
