#!/bin/sh
PATH="$(dirname $0):$PATH"
class=$(sipbmp3-get-config zephyr-class)
host=$(sipbmp3-get-config host)
queue=$(sipbmp3-get-config queue)
instance="$queue-volume@$host"

mixer=$(sipbmp3-get-config mixer)
channel=$(sipbmp3-get-config channel)

muted=$(volume-is-muted)
mute_str=" [$muted]"
if [ "$muted" = "unmuted" ]; then
    mute_str=""
fi

zwrite -c $class -i $instance -d -n -m "$REMOTE_USER set volume $(volume-get)$mute_str" > /dev/null
