#!/bin/sh -e

echo "Editing /etc/printcap..." >&2
if [ ! -e /etc/printcap ]; then
    touch /etc/printcap
fi

if [ ! -e /etc/lprng/printcap ]; then
    ln -s /etc/printcap /etc/lprng/printcap
fi

. /usr/share/debconf/confmodule
db_get gutenbach/printername

printcap=$(cat /etc/printcap | grep ^`echo $RET` || true)
if [ ! -n "$printcap" ]; then
    # add the appropriate entry into /etc/printcap, /etc/lprng/printcap
    echo "$RET" >> /etc/printcap
    echo "  :server" >> /etc/printcap
    echo "  :cm=$RET music spooler" >> /etc/printcap
    echo "  :lp=/dev/null" >> /etc/printcap
    echo "  :if=|/usr/lib/gutenbach/gutenbach-filter" >> /etc/printcap
    echo "  :sd=/var/spool/lpd/$RET" >> /etc/printcap
    echo "  :ml=0:mx=0:sh:sf" >> /etc/printcap
    echo "  :create_files" >> /etc/printcap
fi