#!/bin/bash

found_current=

if [ -e "/var/run/sipbmp3/queue_times" ]; then
    rm "/var/run/sipbmp3/queue_times"
fi

cd /var/spool/lpd/sipbmp3/
for i in $(ls . | grep ^hf); do
    done=$(cat "$i" | grep done)
    if [ ! -n "$done" ]; then
	timestamp=$(cat "$i" | grep ^job_time= | sed 's/.*=//')
	echo "$timestamp:$i" >> /var/run/sipbmp3/queue_times
    fi
done

if [ -e /var/run/sipbmp3/queue_times ]; then
    for i in $(sort /var/run/sipbmp3/queue_times); do
	i=$(echo "$i" | sed 's/.*://')
	prefix="df"${i:2}
	for j in "$prefix"*; do song="$j"; done

	user=$(cat "$i" | grep ^P=)
	user=${user:2}
    
	if [ -e /var/run/sipbmp3/exiftool_data ]; then
	    rm /var/run/sipbmp3/exiftool_data
	fi

	exiftool "$song" >> /var/run/sipbmp3/exiftool_data
	title=$(cat /var/run/sipbmp3/exiftool_data | grep "^Title " | sed 's/.*: //')
	artist=$(cat /var/run/sipbmp3/exiftool_data | grep "^Artist " | sed 's/.*: //')

	if [ -z "$found_current" ]; then
	    host=$(cat "$i" | grep ^H=)
	    host=${host:2}
	    album=$(cat /var/run/sipbmp3/exiftool_data | grep "^Album " | sed 's/.*: //')
	    echo "$user@$host is currently playing: $song"
	    echo "'$title'"
	    echo "by '$artist'"
	    echo "on '$album'"
	    echo ""
	    echo "Coming up in the queue:"
	    found_current="true" 
	else
	    echo "$user: '$title' by '$artist'"
	fi
    done
fi
