#!/bin/sh -e

. /usr/share/debconf/confmodule

if [ ! -d /usr/lib/sipbmp3/config ]; then
    mkdir /usr/lib/sipbmp3/config
fi

echo "Creating /usr/lib/sipbmp3/config/sipbmp3-filter-config.pl..." >&2
if [ ! -e "/usr/lib/sipbmp3/config/sipbmp3-filter-config.pl" ]; then
    touch /usr/lib/sipbmp3/config/sipbmp3-filter-config.pl

    db_get sipbmp3/zephyrclass
    echo "\$zephyr_class = \"$RET\";" >> /usr/lib/sipbmp3/config/sipbmp3-filter-config.pl
    echo "\$hostname = \""`hostname`"\";" >> /usr/lib/sipbmp3/config/sipbmp3-filter-config.pl
    db_get sipbmp3/printername
    echo "\$queue = \"$RET\";" >> /usr/lib/sipbmp3/config/sipbmp3-filter-config.pl
fi