#!/bin/sh

if [ ! -e /etc/printcap ]; then
    touch /etc/printcap
fi

if [ ! -e /etc/lprng/printcap ]; then
    ln -s /etc/printcap /etc/lprng/printcap
fi

printcap=$(cat /etc/printcap | grep '^lprmp3')
if [ ! -n "$printcap" ]; then
    # add the appropriate entry into /etc/printcap, /etc/lprng/printcap
    echo "lprmp3" >> /etc/printcap
    echo "  :server" >> /etc/printcap
    echo "  :cm=lprmp3 music spooler" >> /etc/printcap
    echo "  :lp=/dev/null" >> /etc/printcap
    echo "  :if=|/usr/lib/sipbmp3/sipbmp3-filter" >> /etc/printcap
    echo "  :sd=/var/spool/lpd/lprmp3" >> /etc/printcap
    echo "  :ml=0:mx=0:sh:sf" >> /etc/printcap
    echo "  :create_files" >> /etc/printcap
fi