#!/bin/sh -e

# make sure directories exist for checkpc
echo "Running checkpc..." >&2
if [ ! -d /var/spool/lpd ]; then
    mkdir /var/spool/lpd
    mkdir /var/spool/lpd/%P
else
    if [ ! -d /var/spool/lpd/%P ]; then
	mkdir /var/spool/lpd/%P
    fi
fi
chmod og=rwx /var/spool/lpd
chmod og=rwx /var/spool/lpd/%P

. /usr/share/debconf/confmodule
db_get sipbmp3/printername
/usr/sbin/checkpc -P"$RET" -f