#!/bin/sh
PATH="$(dirname $0):$PATH"

mixer=$(/usr/lib/gutenbach/gutenbach-get-config mixer)
channel=$(/usr/lib/gutenbach/gutenbach-get-config channel)

amixer set $mixer toggle > /dev/null
volume-is-muted

volume-zephyr
